service: lerna-backend


provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-south-1
  memorySize: 512
  timeout: 30

  environment:
    NODE_ENV: ${self:provider.stage}

functions:
  app:
    handler: server.handler
    events:
      - http:
          path: /
          method: ANY
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false

      - http:
          path: /{proxy+}
          method: ANY
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false
